project:
  type: website
  preview:
    port: 7211
    browser: false

website:
  title: "MBAT Club"
  navbar:
    search: false
    pinned: true
    tools:
      - icon: file-earmark-text-fill
        href: https://forms.gle/F8naqubjujRqYnN9A
    right:
      # - text: Events
      #   menu: 
      #     - events.qmd
      # - href: unit_guide.qmd
      #   text: Unit Guide
      - href: course_map.qmd
        text: Course Map
      - text: Events
        href: events.qmd
      - text: Contact us
        href: https://forms.gle/9Tmx25sxkJ6svSma8 
      - text: About
        menu: 
          - href: coc.qmd
            text: Code of Conduct
          - href: people.qmd
            text: The People

format:
  html:
    theme:
      - default
      - brand
      - styles/theme.scss
      - styles/hero.scss
      - styles/calendar.scss
      - styles/discord.scss
      - styles/resources.scss
      - styles/people.scss
    css: styles/styles.css
    toc: false



