---
pagetitle: MBAt Hang
---

# MBAt Hang: Your Alumni & Student Hub 

### for Master of Business Analytics at Monash University

Welcome to MBAt Hang, the central gathering place for current students and alumni of the Business Analytics Masters program. 

This platform is built to strengthen community ties, celebrate achievements, and keep everyone informed about upcoming opportunities. 

Whether you're a recent graduate looking to stay connected or a current student seeking guidance, this space is designed to help you grow, collaborate, and stay in the loop.

:::{.resources-list}
:::{.resource style="text-align: center"}

#### Upcoming events

Curious about what’s happening this semester? Head over to the [Events](/events) tab to explore upcoming workshops, meet-ups, and alumni sessions designed to help you connect, learn, and grow.

:::
:::{.resource style="text-align: center"}

#### Unit Guide

Planning your pathway? Explore the [Course Map](/course-map) to see how each unit connects and discover the study route that works best for you.

:::
:::

<br/>

:::{.resource}

#### Connect with us

Want to connect outside class? Join our Discord server to chat, collaborate, and stay in the loop with fellow students and alumni.

Excited to join in? Submit a request to join the official discord server through [this form](https://forms.gle/F8naqubjujRqYnN9A)!

:::{.discord-server style="width: fit-content; margin: 0 auto"}
```{=html}
<style>
  /* Container */
  .server-card{
    display: flex;
    flex-direction: row;
    align-items:center;
    background:var(--brand-purple);
    padding: 1rem;
    border-radius: 20px;
    box-shadow:var(--shadow);
    color:var(--brand-white);
    margin-bottom: 1rem;
    gap: 2rem;
    cursor: pointer;
    width: fit-content
  }

  /* Text column */
  .server-meta{
    display:flex;
    flex-direction: row;
    gap:4px;
  }

  /* User count chip */
  .users{
    margin-left:auto;
    display:flex;
    align-items:center;
  }
  .users .count{
    text-align:center;
    background:var(--glass);
  }

</style>
<!-- Example card -->
<a href="https://forms.gle/RYSpnoU1caEBikGf8" style="text-decoration: none">
  <div class="server-card" id="server-card-1">
    <div style="padding-left: 2rem"> 
    <div style="font-size: 2rem"> <i class="bi bi-discord"></i> MBAT </div> 
      <div class="server-desc" id="server-desc-1">A fun server for all things Stats, BA and MBAT related !!</div>
    </div>
    <div style="padding-right: 2rem">
    <div class="label" style="display: flex; flex-direction: column; align-items: center">
        <svg viewBox="0 0 24 24" width="36" height="36" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
        <div class="count" id="user-count-1">33</div>
      </div>
    </div>
  </div>
</a>

<script>
  fetch("https://discord.com/api/invites/j7C7kGTXfJ")
    .then((resp) => {
    if(resp.ok) {
      return resp.json()
    } else {
    throw new Error("Discord server data broken")
    }
    })
    .then((json) => {
      console.log(json)
      document.querySelector(".server-name > span").innerHTML = json.guild.name
      document.querySelector(".server-desc").innerHTML = json.guild.description
      document.querySelector("#user-count-1").innerHTML = json.profile.member_count
    })
</script>
```

:::




:::

